server:
  port: 8080
  error:
    include-message: always

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jpworksdb
    username: developer_dba
    password: password